### PR TITLE
Front React module

### PR DESCRIPTION
**Pull request by glebfox**
This PR adds the **front** module based on React along with separate user and role.

In addition, the following changes are made to the model:
1. Added the `color` attribute to `PetType` for more graceful representation in UI.
2. Added the `generation` attribute to `Pet` in order to show how to work with enums in react.

### CODE REVIEW

**Comment by mariodavid** [comment]
Hi,

looks good to me. 

One thing that I'm not sure about is that if the code should really be in this repository, or if it should be in this repository: https://github.com/cuba-platform/cuba-petclinic

Currently we don't actively promote this repo here in the guides or anywhere else. Instead it is just used as a fork of the original one (https://github.com/cuba-platform/cuba-petclinic) to store the slight delta for the deployment (e.g. the custom database for each user session). The one that is used in any communication is this one: https://github.com/cuba-platform/cuba-petclinic

But this change seems to be more like a general thing that you want to promote, correct? If so, I think it would make more sense to create a PR in the original (promoted) repo then sync the changes to this repo in order to deploy it accordingly. But this would have the consequence that every new guide we create will also inherit the react front module.

WDYT?

**Comment by knstvk** [comment]
Hi Mario
I think we shouldn't add it to the original repo, for the reason you mentioned. 
We would like to present the React UI separately from other guides, so including it here is only for simplicity of maintaining the online demo.

**Comment by glebfox** [comment]
Hi Mario,

We have a separate petclinit-react repo (https://github.com/cuba-platform/cuba-petclinic-react), but we don't want to add code for the deployment purpose to it as well as have two identical demo apps, so that I added required code to this repo.

**Comment by mariodavid** [comment]
Ok, i wasnt aware of that extra repo... that makes sense then :+1:

**Pull request merged**
